"""insert

Revision ID: 887e9fc64eed
Revises: 657f807b2291
Create Date: 2024-08-03 12:33:32.000142

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "887e9fc64eed"
down_revision: Union[str, None] = "657f807b2291"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    query_hotels = """
    INSERT INTO public.hotels (id,name,"location",services,rooms_quantity,image_id) VALUES
	 (1,'Cosmos Collection Altay Resort','Республика Алтай, Майминский район, село Урлу-Аспак, Лесхозная улица, 20','["Wi-Fi", "Парковка"]',23,2),
	 (2,'Skala','Республика Алтай, Майминский район, поселок Барангол, Чуйская улица 40а','["Wi-Fi", "Парковка"]',23,2),
	 (3,'Ару-Кёль','Республика Алтай, Турочакский район, село Артыбаш, Телецкая улица, 44А','["Парковка"]',30,3),
	 (4,'Гостиница Сыктывкар','Республика Коми, Сыктывкар, Коммунистическая улица, 67','["Wi-Fi", "Парковка", "Тренажёрный зал"]',67,1),
	 (5,'Palace','Республика Коми, Сыктывкар, Первомайская улица, 62','["Wi-Fi", "Парковка", "Кондиционер в номере"]',22,5),
	 (6,'Bridge Resort','посёлок городского типа Сириус, Фигурная улица, 45','["Wi-Fi", "Парковка", "Кондиционер в номере"]',30,6);
	 """
    op.execute(query_hotels)
    query_rooms = """
    INSERT INTO public.rooms (id,hotel_id,name,description,price,services,quantity,image_id) VALUES
	 (1,1,'Улучшенный с террасой и видом на озеро',NULL,24500,'["Бесплатный Wi-Fi", "Кондиционер (с климат-контролем)"]',5,7),
	 (2,1,'Делюкс Плюс',NULL,22450,'["Бесплатный Wi-Fi", "Кондиционер"]',10,8),
	 (3,1,'Номер на 2-х человек',NULL,4570,'["Бесплатный Wi-Fi"]',15,9),
	 (4,1,'Номер на 3-х человек',NULL,4350,'["Бесплатный Wi-Fi"]',8,10),
	 (5,2,'Номер полулюкс семейный (с двуспальной кроватью)',NULL,7080,'["Холодильник"]',20,11),
	 (6,2,'2-комнатный номер люкс комфорт',NULL,9815,'["Холодильник"]',10,12),
	 (7,4,'Стандарт двухместный',NULL,4300,'["Бесплатный Wi-Fi", "Холодильник"]',20,13),
	 (8,4,'Стандарт улучшенный ПЛЮС',NULL,4720,'["Бесплатный Wi-Fi", "Холодильник"]',35,14),
	 (9,5,'Номер стандарт 2 спальная кровать (с завтраком)',NULL,5000,'["Бесплатный Wi-Fi", "Ванная комната", "Кондиционер"]',15,15),
	 (10,6,'Номер делюкс',NULL,8000,'["Бесплатный Wi-Fi"]',7,16),
	 (11,6,'Стандарт (типовой корпус)',NULL,8125,'["Бесплатный Wi-Fi"]',45,17);
	 """
    op.execute(query_rooms)

    query_users = """
    INSERT INTO public.users (id,email,hashed_password) VALUES
	 (1,'fedor@moloko.ru','tut_budet_hashed_password_1'),
	 (2,'sharik@moloko.ru','tut_budet_hashed_password_2'),
	 (3,'test@test.com','$2b$12$RYIJ81.SlJNosol4U5ZZxub5pMbxLT5fUc8CESSghIZNtFx5F8DqW'),
	 (4,'test@ttest.com','$2b$12$IjxgnQe4FMp7xvTAHUnnh.2AmkyPIRO4ldCSOfmY7EyEm/gsLLzxq'),
	 (5,'test@tteest.com','$2b$12$mKsvwTEKq7QM0RfZMS.7HO6sCc/E5pHenYE7IGs44SbjJuZU8V7iy'),
	 (6,'test@tteesdst.com','$2b$12$za8EWVFkYTxAPH2nMBRdVeaiufYbbECdMC8/jy9L4kG3jl8ydHLKC'),
	 (7,'tedst@tteesdst.com','$2b$12$wP8zo6zamPrZ/EmZNcLC3.ZpHMdP2lBZKQOg/wUlRJQ/GOqBFCQES'),
	 (8,'user@example.com','$2b$12$Eu03tejW2n629vYPycfnOuJR0gC3eA87vqucCHkeOxpBkvE//9Csa'),
	 (9,'usder@example.com','$2b$12$4yIiEWOITpF6ElW0qewcpu.nGkKo2Gha.YwPxg/cJCTICYHLA/1Pm'),
	 (10,'user1@example.com','$2b$12$B3rfHU7ej.VIxLa8fATd1u50D/9qvVVg/qzUdS9qGpbNN6Lb27cqK');
	 """
    op.execute(query_users)

    query_bookings = """
        INSERT INTO public.bookings (id,room_id,user_id,date_from,date_to,price) VALUES
    	 (1,1,1,'2023-06-15','2023-06-30',367500),
    	 (2,7,2,'2023-06-25','2023-07-10',64500);
        """
    op.execute(query_bookings)

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
